name: "Warn about Merge Markers in package-lock.json"

on: [pull_request, push]

jobs:
  check-merge-markers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.8
      - run: npm install --ignore-scripts
      - name: Check for merge markers
        run: npm run check:conflicts
