name: "Check for Merge Markers in package-lock.json"

on: [pull_request, push]

jobs:
  check-merge-markers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for merge markers
        run: |
          if grep -qE '<<<<<<<|=======|>>>>>>>' package-lock.json; then
            echo "ERROR: Merge markers found in package-lock.json!"
            exit 1
          else
            echo "No merge markers found."
          fi
