name: Lighthouse CI

on:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.8
      - name: Install dependencies
        run: npm install
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Set CHROME_PATH
        run: echo "CHROME_PATH=$(which google-chrome)" >> $GITHUB_ENV
      - name: Run Lighthouse CI
        run: npx -y lighthouse-ci autorun --config=lighthouserc.json --failOn=all
      - name: Upload Lighthouse reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: lighthouse-reports
